FROM openjdk:17-jdk-alpine
MAINTAINER Siak Hooi
COPY target/hellospringbootmicroservice-0.1.0.jar hellospringbootmicroservice-0.1.0.jar
ENTRYPOINT ["java","-jar","/hellospringbootmicroservice-0.1.0.jar"]
