FROM eclipse-temurin:21.0.2_13-jre-alpine
MAINTAINER Siak Hooi
COPY hellospringbootmicroservice-0.4.0.jar hellospringbootmicroservice-0.4.0.jar
ENTRYPOINT ["java","-jar","/hellospringbootmicroservice-0.4.0.jar"]
