deployment:

# replicaCount: 1              # set the deployment spec.replicas

  image:
    tag: "0.10.0"
#   pullPolicy: IfNotPresent   # set the deployment container pullPolicy

  resources:             # enable to set deployment container resources
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi  

  readinessProbe:
    enabled: true              # enable the readinessProbe
#   initialDelaySeconds: 10
#   periodSeconds: 5
#   timeoutSeconds: 1
#   successThreshold: 1
#   failureThreshold: 1
  livenessProbe:
    enabled: true              # enable the livenessProbe
#   initialDelaySeconds: 10
#   periodSeconds: 5
#   timeoutSeconds: 1
#   successThreshold: 1
#   failureThreshold: 1
  startupProbe:
    enabled: true              # enable the startupProbe
#   initialDelaySeconds: 10
#   periodSeconds: 5
#   timeoutSeconds: 1
#   successThreshold: 1
#   failureThreshold: 10
