apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    {{- include "chart-labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: hello-springboot-microservice
  template:
    metadata:
      labels:
        app: hello-springboot-microservice
      {{- include "chart-labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "image-name" . }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
{{- if .Values.deployment.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: {{ (.Values.deployment.readinessProbe.initialDelaySeconds) | default 10 }}
            periodSeconds: {{ (.Values.deployment.readinessProbe.periodSeconds) | default 5 }}
            timeoutSeconds: {{ (.Values.deployment.readinessProbe.timeoutSeconds) | default 1 }}
            successThreshold: {{ (.Values.deployment.readinessProbe.successThreshold) | default 1 }}
            failureThreshold: {{ (.Values.deployment.readinessProbe.failureThreshold) | default 1 }}
{{- end }}
{{- if .Values.deployment.livenessProbe.enabled  }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: {{ (.Values.deployment.livenessProbe.initialDelaySeconds) | default 10 }}
            periodSeconds: {{ (.Values.deployment.livenessProbe.periodSeconds) | default 5 }}
            timeoutSeconds: {{ (.Values.deployment.livenessProbe.timeoutSeconds) | default 1 }}
            successThreshold: {{ (.Values.deployment.livenessProbe.successThreshold) | default 1 }}
            failureThreshold: {{ (.Values.deployment.livenessProbe.failureThreshold) | default 1 }}
{{- end }}
{{- if .Values.deployment.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: {{ (.Values.deployment.startupProbe.initialDelaySeconds) | default 10 }}
            periodSeconds: {{ (.Values.deployment.startupProbe.periodSeconds) | default 5 }}
            timeoutSeconds: {{ (.Values.deployment.startupProbe.timeoutSeconds) | default 1 }}
            successThreshold: {{ (.Values.deployment.startupProbe.successThreshold) | default 1 }}
            failureThreshold: {{ (.Values.deployment.startupProbe.failureThreshold) | default 1 }}
{{- end }}
{{- if .Values.deployment.resources  }}
          resources:
{{ .Values.deployment.resources | toYaml | indent 12 }}
{{ end }}