apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "helm_chart_name_version" . }}
spec:
  selector:
    app: hello-springboot-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
