name: Build hello-springboot-microservice:latest

on: 
  workflow_dispatch:
  workflow_call:
      secrets:
        REGISTRY_PASSWORD_DOCKER:
          required: true
      inputs:
        push-images:
          required: true
          type: boolean
            

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: deliverables
          path: ./
      - run: ls -l
      - run: cat release.env >> $GITHUB_ENV
      - uses: docker/login-action@v3
        with:
          username: siakhooi
          password: ${{ secrets.REGISTRY_PASSWORD_DOCKER }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./deploy/docker/Dockerfile
          push: ${{ inputs.push-images }}
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest,${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_VERSION }}
