name: Build with Maven

on: workflow_call

jobs:
  build-with-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: mvn verify
      - uses: actions/upload-artifact@v4
        with:
          name: deliverables
          path: ./target/hellospringbootmicroservice-*.jar
      - uses: actions/upload-artifact@v4
        with:
          name: target
          path: ./target/
