name: Build hello-springboot-microservice:latest

on: 
  workflow_dispatch:
  workflow_call:
      secrets:
        REGISTRY_PASSWORD_DOCKER:
          required: true

jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: deliverables
          path: ./
      - run: ls -l
      - uses: docker/login-action@v3
        with:
          username: siakhooi
          password: ${{ secrets.REGISTRY_PASSWORD_DOCKER }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./deploy/docker/Dockerfile
          push: true
          tags: siakhooi/hello-springboot-microservice:latest
