name: Deploy GitHub Release Assets - Helm Chart

on:
  workflow_call:
    secrets:
      TOKEN_TO_UPLOAD_ASSETS:
        required: true

jobs:
  deploy_github_release_assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: helm-chart
          path: ./
      - run: ls -l
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./hello-springboot-microservice-*.tgz
