name: Deployment
on:
  release:
    types: [created]

jobs:
  build-with-maven:
    uses: ./.github/workflows/build-with-maven.yml

  release-assets:
    needs: build-with-maven
    uses: ./.github/workflows/deploy-github-release-assets.yml
    secrets:
      TOKEN_TO_UPLOAD_ASSETS: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}

  build-docker-images:
    needs: build-with-maven
    uses: ./.github/workflows/build-docker-image.yml
    secrets:
      REGISTRY_PASSWORD_DOCKER: ${{ secrets.REGISTRY_PASSWORD_DOCKER }}
    with:
      push-images: true
