name: Deployment
on:
  release:
    types: [created]

jobs:
  build-with-maven:
    uses: ./.github/workflows/build-with-maven.yml

  release-assets:
    needs: build-with-maven
    uses: ./.github/workflows/deploy-github-release-assets.yml
    secrets:
      TOKEN_TO_UPLOAD_ASSETS: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
